version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: earthworm
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # 如果使用 Docker MySQL，需要先停掉本机 MySQL80 服务
    # net stop MySQL80
    ports:
      - 3306:3306
  testdb:
    # 测试环境使用不同端口避免冲突
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: earthworm_test
    volumes:
      - mysql_test_data:/var/lib/mysql
    ports:
      - 3307:3306
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - data:/var/lib/redis
    ports:
      - 6379:6379
  testRedis:
    image: redis:5-alpine
    volumes:
      - data:/var/lib/test-redis
    ports:
      - 6380:6379
  logto:
    restart: always
    depends_on:
      logtoPostgres:
        condition: service_healthy
    image: svhd/logto:1.18.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3010:3010
      - 3011:3011
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@logtoPostgres:5432/logto
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - PORT=3010
      - ADMIN_PORT=3011
      - ENDPOINT
      - ADMIN_ENDPOINT
  logtoPostgres:
    restart: always
    image: postgres:14-alpine
    user: root
    volumes:
      - "./.volumes/logto_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
  mysql_test_data:
    driver: local
  data:
    driver: local
