version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: earthworm
    volumes:
      - data:/var/lib/mysql/main-data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
  testdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: earthworm_test
    volumes:
      - data:/var/lib/mysql/test-data
    ports:
      - 3307:3306

volumes:
  data:
    driver: local